# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7DLZgqks7AV8Oaqfu7I2lgj8C6ui836
"""

mensajeint = 3
mensajefloat = 3.5
mensajestr = "Hola Mundo"
print("Esto es un entero",mensajeint,"\nEsto es un Float",mensajefloat,"\nEsto es un String",mensajestr)

num = int(input("Ingrese un numero "))
if num % 2 == 0:
  print("El numero: ",num," Es Par")
else:
  print("El numero: ",num," Es Impar")

listanumeros = [2,3,5,1,6]
tamaño = len(listanumeros)
contador = 0
while contador < tamaño:
  print(listanumeros[contador] * listanumeros[contador])
  contador += 1

while True:
  decision = input("Ingresa si quieres para o no, Digita Si o No ")
  if decision == "Si":
    break
print("Decidistes Parar!!")

ListaDatos = ["Camilo Gonzalez","Felipe Chavez","Juana Ruiz","Daniel Naverus"]
for nombre in ListaDatos:
  print(nombre)

diccionario = {
  "Nombre": "Sara",
  "Correo": "hola@gmail.com",
}
print(diccionario)

diccionario['Nombre'] = input("Actualizar Nombre ")
print(diccionario)

num1 = int(input("Ingrese el numero 1 "))
num2 = int(input("Ingrese el numero 2 "))
print("Suma: +\n","Resta: -\n","Multiplicacion: *\n","Division: /\n ")
operacion = input("Que operacion deseas hacer: ")
if operacion == "+":
  resultado = num1 + num2
  print("El resultado de la suma es: ",resultado)
elif operacion == "-":
  resultado = num1 - num2
  print("El resultado de la resta es: ",resultado)
elif operacion == "*":
  resultado = num1 * num2
  print("El resultado de la multiplicacion es: ",resultado)
elif operacion == "/":
  resultado = num1 / num2
  print("El resultado de la division es: ",resultado)

from ast import Break
import random
numaleatorio = random.randint(1,100)

while True:
  num = int(input("Ingrese un numero: "))
  if num == numaleatorio:
    print("Ganastes")
    break
  elif num > numaleatorio:
    print("El numero que ingresastes es mayor al numero aleatorio")
  else:
    print("El numero que ingreastes es menor al numero aleatorio")